package org.kissfarm.shared.api;

import java.io.Serializable;

public class NodeIdentity implements Serializable {
	private static final long serialVersionUID = -7338313055017570385L;

	/**
	 * Auto-generated by agent
	 */
	private String id;

	/**
	 * Host name
	 */
	private String hostName;

	private String publicIp;

	/**
	 * CSV of tags
	 */
	private String tags;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHostName() {
		return hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	public String getPublicIp() {
		return publicIp;
	}

	public void setPublicIp(String publicIp) {
		this.publicIp = publicIp;
	}

	public String getTags() {
		return tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Override
	public String toString() {
		return "NodeIdentity [id=" + id + ", hostName=" + hostName + ", publicIp=" + publicIp + ", tags=" + tags + "]";
	}
}
